### ISSUE TITLE
Fails on already pretty JSON

### ISSUE THREAD

**Issue by turadg** [jmhodges/jsonpp#4]
This works:
```json
{"id": 28345}
````

But this:
```json
{
  "id": 28345
}
````

gives an error:
````
ERROR: Broken json on line 1: unexpected end of JSON input
  Context: {
````

**Comment by Vramin** [comment]
Just went through the same exercise this afternoon, every file I tried to parse exited with:

ERROR: Broken json on line 1, char 2: unexpected end of JSON input
  Context: {

Went back to jslint which thinks my JSON is just dandy.

It's documented, but it still seems like an odd behavior.

**Comment by wader** [comment]
For people ending up here: try the program jq, e.g. `cat file.json | jq .`

**Comment by da-mobenga** [comment]
@wader, thanks

**Comment by wader** [comment]
@da-mobenga :+1:
